#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-mistune
Version  : 2.0.1
Release  : 46
URL      : https://files.pythonhosted.org/packages/f6/e1/14e6e4b3a29592a5816fabf2c65ea093516197ba09fcb60732e95de513da/mistune-2.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/f6/e1/14e6e4b3a29592a5816fabf2c65ea093516197ba09fcb60732e95de513da/mistune-2.0.1.tar.gz
Summary  : A sane Markdown parser with useful plugins and renderers
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-mistune-license = %{version}-%{release}
Requires: pypi-mistune-python = %{version}-%{release}
Requires: pypi-mistune-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: mistune
Provides: mistune-python
Provides: mistune-python3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
Mistune
=======
A fast yet powerful Python Markdown parser with renderers and plugins.

%package license
Summary: license components for the pypi-mistune package.
Group: Default

%description license
license components for the pypi-mistune package.


%package python
Summary: python components for the pypi-mistune package.
Group: Default
Requires: pypi-mistune-python3 = %{version}-%{release}

%description python
python components for the pypi-mistune package.


%package python3
Summary: python3 components for the pypi-mistune package.
Group: Default
Requires: python3-core
Provides: pypi(mistune)

%description python3
python3 components for the pypi-mistune package.


%prep
%setup -q -n mistune-2.0.1
cd %{_builddir}/mistune-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641455662
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mistune
cp %{_builddir}/mistune-2.0.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mistune/f763a35f662facb7d39a4fd7c3872b311855bc43
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mistune/f763a35f662facb7d39a4fd7c3872b311855bc43

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
